on:
  schedule:
    - cron:  '0 17 * * *'
  workflow_dispatch:   

name: Azure Container Instance Deployment

jobs:

  deploy-docker-image-to-aci:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure CLI login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az container start \
          -g ${{ secrets.RESOURCE_GROUP }} \
          -n immobot
          az logout
          az cache purge
          az account clear
