on:
  workflow_dispatch:   

name: Azure Container Instance Deployment

jobs:

  deploy-docker-image-to-aci:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure CLI login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az container create \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name immobot \
          --image ${{ secrets.DOCKERHUB_USERNAME }}/immo:latest \
          --restart-policy Never \
          --sku Standard \
          --secure-environment-variables 'MONGO_DB_URI'='${{ secrets.MONGO_DB_URI }}'
          az logout
          az cache purge
          az account clear
